### ISSUE TITLE
Adding Vertical Today Marker

### ISSUE THREAD

**Issue by jzzh** [ogobrecht/apex-plugin-dhtmlx-gantt#15]
I'm having trouble with adding a vertical marker.

Documentation reference:
https://docs.dhtmlx.com/gantt/desktop__markers.html#todaysmarker

1. activated "Vertical Marker" in the Load Extension attribute settings.

2.  added this code to Before Init JS Code (also tried After Init JS Code)

```
var date_to_str = gantt.date.date_to_str(gantt.config.task_date);
var id = gantt.addMarker({ 
    start_date: new Date(), 
    css: "today", 
    text: "Today", //the marker title
    title:date_to_str( new Date())
});
```

On Page load the marker shows up for some miliseconds and then disappears again.

I also added it to a dynamic action (mont/year re-scaling).
In the DA the code works and the marker shows, but the problem is that you have to click a button first.

thanks for any help,
Jochen

**Comment by jzzh** [comment]
**Workaround:**
Create a dynamic action "After Refresh" of the Gantt Region.


Execute Javascript Code:

```
var date_to_str = gantt.date.date_to_str(gantt.config.task_date);
var id = gantt.addMarker({ 
    start_date: new Date(), 
    css: "today", 
    text: "Today", //the marker title
    title:date_to_str( new Date())
});
gantt.render();
```

Note the call to **gantt.render();** in the end.

**Comment by ogobrecht** [comment]
Hi Jochen,

thank you for your feedback and also the workaround :-)

I think about to add a "After Refresh JS Code" section...
... my first thought, let me see what I can do. Will take some time because I have currently limited resources...

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Jochen,

I have released a [new version](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/releases/tag/v0.11.1) which includes the mentioned "After Refresh JS Code" section. You are now free to use this section for your marker code or use a dynamic action as you already do.

Please have a look at your region attributes since many things have changed in the background because of newer library code (also see the [change log](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt#changelog)).

Best regards
Ottmar

**Comment by jzzh** [comment]
Great !  
Thanks for the notification Ottmar.

**Comment by ogobrecht** [comment]
You are welcome. Thanks for opening the issue and showing me the problem!

Last note: If you use the "After Refresh JS Code" attribute in the plugin, then please do not call `gantt.render()` by yourself as you do within the dynamic action.
