### ISSUE TITLE
Installed the DEMO APP but the application running without the gantt chart

### ISSUE THREAD

**Issue by shiaohuihoh** [ogobrecht/apex-plugin-dhtmlx-gantt#16]
Dear contributor,

I've installed the imported the file "apex-plugin-dhtmlx-gantt-0.9.0-demo-app.sql" into APEX and tried to run it without changing anything. However, there isn't any gantt chart appear on the screen. Please refer to the attached file for the screen shot.
Can you please help?

Thanks,
Katie

![demo-app](https://user-images.githubusercontent.com/48337763/69301102-3a73fa00-0c69-11ea-9440-94b5102ed15d.JPG)

**Comment by ogobrecht** [comment]
Hi Katie,

sorry for my late response: I tried to install the demo app into apex.oracle.com and I had no problems:
![image](https://user-images.githubusercontent.com/10425445/69824283-8f84b280-120b-11ea-8196-82ed6aa803b5.png)

Did you checked the console of your browser for any errors? It seems you modified something because the screenshot of your app looks not like the provided demo app. Did you suppressed the installation of the supporting objects or missed to change the regions query to support your own datamodel?

I need some more details to be able to help...

Best regards
Ottmar

**Comment by shiaohuihoh** [comment]
Hi Ottmar,

Thank you for your reply.
I think it's nothing to do with your application.
It might be something to do with my apex environment.
It's complaining it failed to load the css and js files.
I've googled the error and it might be something to do with ORDS
configuration, but it's been configured as it should be. I have no idea
where else to look for now.
Thank you for your response by the way.

Cheers,
Katie

[image: image.png]

**Comment by ogobrecht** [comment]
Hi Katie,

did you install a new version of APEX after the ORDS installation?

If so, you should try to validate your ORDS installation. Please see also this [blog post](https://www.oracle-and-apex.com/apex-static-files-not-served-ords-returns-404-or-why-reading-logfiles-help/) as an example.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Katie,

any news - is your APEX instance working now?

As I think your problem has nothing to do with my plug-in or sample app I will close now the issue.

Best regards
Ottmar
