### ISSUE TITLE
Filter on Ganttchart in Oracle apex

### ISSUE THREAD

**Issue by ShantveerS** [ogobrecht/apex-plugin-dhtmlx-gantt#7]
Dear Sir,
I have few textfields and drop down on my gantt chart page. I want to filter the gantt chart based on these fields. I can do it, but I need to submit the page to refresh the gantt chart data. 

How can I filter Gantt chart dynamically, without submitting the page. ?

Thanks,
Shantveer

**Comment by ShantveerS** [comment]
Also, I have huge data in Gantt Chart and How can I improve the performance as Gantt chart getting loaded very slowly.

**Comment by ogobrecht** [comment]
Dear Shantveer,

the Gantt chart can be refreshed with a partial page refresh (AJAX) like many other regions in APEX. All you have to do is to create a dynamic action on a button click or a item change and as the true action select "Refresh", as selection type "Region" and as Region your Gantt chart:

<img width="1195" alt="gantt1" src="https://user-images.githubusercontent.com/10425445/29087379-ffd1b0a2-7c75-11e7-85e6-d7c09af711bd.png">

To bring your items needed for the region query into session state you have to provide them under "Page Items to Submit" - in my example are no items selected for session state because the query does not need them at the moment:

<img width="1267" alt="gantt2" src="https://user-images.githubusercontent.com/10425445/29087541-9899ac72-7c76-11e7-9c63-ea49ec388aee.png">

I have no idea how many data you load at the moment and where your bottleneck is - could be anything (query performance, network speed...). Normally the JavaScript in the frontend will not be the problem. As an first test please simply put #TIMING# in the footer of your Gantt chart region. APEX will then provide the runtime of your query in seconds in the region footer. You can do this trick also in other regions like classic or interactive reports.

Hope this helps, best regards
Ottmar
