### ISSUE TITLE
Dynamic Loading in Gantt Chart

### ISSUE THREAD

**Issue by ShantveerS** [ogobrecht/apex-plugin-dhtmlx-gantt#8]
Hi,

I have two tables, one for parent data and another for child data. As it has huge data, I want to load the parent data on page load and then on click of + sign (on expand) want to load all child records from child table.

Please let me know how can we do this in Oracle Apex plugin.

**Comment by ShantveerS** [comment]
Also, Will client side filtering works if in above situation ?

**Comment by ShantveerS** [comment]
How can I use dynamic loading in oracle apex plugin ?

**Comment by ogobrecht** [comment]
Hi Shantveer,

I can't imagine a Gantt chart where you have so many items, that this would be problem to render. And if so I think your users don't have fun to look at such a big Gantt chart or your database administrators have no fun with your system because of the slow queries.

I strongly recommend to use the ability to work with bind variables in your query and implement any useful filter for your data - like a select list for a project or project group. You can simply set items into session state for the query by configuring them under the region query in the appropriate field (I think it is called "Items to submit" or something else - I had no look at the moment - you will find it) and this will also work with the AJAX refresh within a dynamic action (action refresh, type region).

By using this APEX mechanism you will be able to define some sort of interactivity with the user and APEX is keeping your users informed that the region is refreshed with the animation of a spinner icon.

In the current implementation there is no other way to do a refresh - the Gantt chart is cleared first and then the data is filled in. Depending on the data format you are providing (XML or JSON) there is also  some preparsing done - if you are interested, you can have a look [here](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/blob/master/server/plugin-dhtmlxgantt-helper.js) starting on line 230. In line 301 and up the gantt API is used to load the data into the chart:

```javascript
        //push data into gantt chart
        try {
            gantt.clearAll();
            gantt.parse(plugin_dhtmlxGantt.dataParsed);
        } catch (e) {
            plugin_dhtmlxGantt.util_logError("vendor base library was unable to use your data: " + e.message);
        }
```

If you like you can setup a page process which delivers data in the correct needed JSON format (see docs [here](https://docs.dhtmlx.com/gantt/desktop__how_to_start.html#step4loaddatatotheganttchart)) and call only the `gantt.parse` method - then the library is merging your data into the existing data. See also the extensive Gantt API - [here the parse method](https://docs.dhtmlx.com/gantt/api__gantt_parse.html) as an example.

But please rethink your current query before you go this way.

Hope this helps, best regards
Ottmar
